### ISSUE TITLE
python error 

### ISSUE THREAD

**Issue by dkrefta** [TomAnthony/itermocil#125]
Hey guys, does somebody know how to fix this error? Thanks very much!
```

Traceback (most recent call last):
  File "/opt/homebrew/bin/itermocil", line 33, in <module>
    sys.exit(load_entry_point('itermocil==1.0.0', 'console_scripts', 'itermocil')())
  File "/opt/homebrew/Cellar/itermocil/1.0.2/libexec/lib/python3.10/site-packages/itermocil.py", line 731, in main
    instance = Itermocil(filepath, here=args.here, cwd=cwd)
  File "/opt/homebrew/Cellar/itermocil/1.0.2/libexec/lib/python3.10/site-packages/itermocil.py", line 58, in __init__
    if 'pre' in self.parsed_config:
TypeError: argument of type 'NoneType' is not iterable
jako aborted.
```

**Comment by godbout** [comment]
> Hey @godbout, what's up? Here is:

wait i know this one. the sky? the sun?

i've pasted your yml. it works here:

https://user-images.githubusercontent.com/121373/174953214-ef8e1fc2-35f8-4015-b949-a13d68f3314b.mp4

my guess is that your installation is not correct.

reading this `sys.exit(load_entry_point('itermocil==1.0.0', 'console_scripts', 'itermocil')())` feels strange to me. the `1.0.0`. but maybe i'm wrong. 

also you're on a M1 it seems, i'm not. so can't check more.

tbh i just updated Itermocil's code so that it works on Monterey/Python 3. but the next day i forgot everything i did and it works. so my comments above might not be correct.

sorry, all i can do. other priorities. hopefully someone else will save you.

**Comment by godbout** [comment]
running `iTermocil --version` on my machine returns `1.0.0`. so maybe that strange thing i'm referring to above is correct. don't know. but your yml doesn't contain errors and work with the latest version of iTermocil. so it's a bit weird.

**Comment by dkrefta** [comment]
Yeah, perhaps is a problem with the m1 but I followed the readme but seems strange the installation with brew, I had the problem with rosetta 2 but I solved but now I don't know, which folder your iTermocil is installed?! can you tell me, please.

**Comment by dkrefta** [comment]
iTermocil --version
1.0.0 for me as well

**Comment by godbout** [comment]
> Yeah, perhaps is a problem with the m1 but I followed the readme but seems strange the installation with brew, I had the problem with rosetta 2 but I solved but now I don't know, which folder your iTermocil is installed?! can you tell me, please.

i don't know either LOL

try `which itermocil`. that should give you the place.

your log says it can't parse the yml. so i'd guess now that it's the python version that is the issue? what python version are you running. you're on Monterey, right?

**Comment by dkrefta** [comment]
yeah dude, and also I was checking the copy of yml and the folder that was copying was coming with a blank file lol haha
then I changed the root: 'the path of the app' 
then jako now is running so it's a problem with the yml and perhaps the copy of the files, so for now I'm closing the issue thx very much for the help after you said about the yml file I was debugging there and with and I trying the echo with the var there was nothing there lol

**Comment by godbout** [comment]
ok i'm not drunk but reading you sounds like i'm drunk. glad it's solved though. that'll be 5 thousand dollars thanks.

**Comment by dkrefta** [comment]
@godbout not I'm not drunk hahaha but perhaps I talk too much haha
