### ISSUE TITLE
somehow possible to send command after first commands are executed?

### ISSUE THREAD

**Issue by tobsn** [TomAnthony/itermocil#22]
I want to connect via "eb ssh" to an elastic beanstalk instance - their ssh wrapper does not allow to execute commands via the invoking cli after opening the shell. ssh -t etc. 
is it somehow possible to type into the open shell, send a command, etc.?

**Comment by TomAnthony** [comment]
The problem is that you want to send your second commands to an ssh instance and as you note - their ssh wrapper doesn't have that built in.

iTermocil works in a different ways for the new iTerm builds (2.9+ which are still in beta) and the stable builds. But you could use 'write text' in Applescript to do what you wanted.

iTermocil actually allows you to output the complete Applescript that it is uses (--debug) flag, so what you could do is create your iTermocil script and then generate the Applescript and edit that Applescript to use for your purposes.

Assuming a stable release of iTerm, you might have a block that looks like this:

```
       tell second session of current terminal
		write text "eb ssh -n 1"
		set name to "ambassador"
	end tell
```

Which you would need to edit to be something like:

```
       tell second session of current terminal
		write text "eb ssh -n 1"
		delay 3
		write text "whoami"
		set name to "ambassador"
	end tell
```

It is a bit of a hack, but it should work for your purposes.
